<?php

/**
 * Load services definition file.
 */
$settings['container_yamls'][] = __DIR__ . '/services.yml';

/**
 * Load settings generated by pantheon-systems/drupal-integrations.
 */
include __DIR__ . '/settings.pantheon.php';

/**
 * Keep deployable Drupal configuration in the repository root.
 */
$settings['config_sync_directory'] = dirname(__DIR__, 3) . '/config';

/**
 * Load local overrides generated by tools such as DDEV.
 */
$local_settings = __DIR__ . '/settings.local.php';
if (file_exists($local_settings)) {
  include $local_settings;
}
